In [16]:
#1.3.1
import numpy as np

arr = np.zeros((8, 8)) #создание матрицы из нулей
arr[::2, ::2] = 1 #чётные элементы чётных строк равны 1
arr[1::2, 1::2] = 1 #нечётные элементы нечётных строк равны 1

print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [36]:
#1.3.2

arr =  np.zeros((5, 1)) + np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [37]:
#1.3.3

arr = np.random.random((3, 3, 3))

print(arr)

[[[0.31740383 0.26570743 0.91638234]
  [0.80155591 0.5801956  0.60500947]
  [0.35334836 0.39044138 0.70093568]]

 [[0.54180277 0.21897638 0.67910348]
  [0.57526156 0.4172934  0.21926901]
  [0.36497617 0.15212809 0.61209309]]

 [[0.07516526 0.57628391 0.2033039 ]
  [0.19024944 0.52614107 0.34715681]
  [0.93328559 0.35032216 0.92735638]]]


In [55]:
#1.3.4
size = (3, 3)

arr = np.zeros(size)

arr[0, :] = 1  # Top row
arr[-1, :] = 1  # Bottom row
arr[:, 0] = 1  # Left column
arr[:, -1] = 1  # Right column

print(arr)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [52]:
#1.3.5
arr = np.random.random((10))
arr.sort()
arr = arr[::-1]

print(arr)

[0.83313825 0.79458009 0.7128688  0.70810514 0.63945703 0.57957748
 0.47749483 0.47653968 0.43967304 0.22385339]


In [60]:
#1.3.6

arr = np.random.random((10, 10))

print("Shape:", arr.shape, "Size:", arr.size, "Dim:", arr.ndim)

Shape: (10, 10) Size: 100 Dim: 2


In [67]:
#2.2.1
import pandas as pd

#Создание двух точек a и b
a = pd.Series([1, 2, 3])
b = pd.Series([1, 1, 3])

#Вычисление евклидова расстояния
distance = np.sqrt(np.sum((a - b) ** 2))

print(distance)

1.0


In [71]:
#2.3.2

url = "https://raw.githubusercontent.com/akmand/datasets/main/elevators.csv"

data = pd.read_csv(url)

print(data)

         1   2     3     4    5   6   7      8    9      10      11      12  \
0     -178  40 -0.11  0.13  1.1  -9 -12 -0.011  0.0 -0.0007 -0.0007 -0.0007   
1     -122   9  0.27  0.05  0.0 -10  -2 -0.005  0.4 -0.0007 -0.0007 -0.0007   
2      196 -10 -0.44  0.10  0.6 -10  -7  0.003  0.2 -0.0006 -0.0006 -0.0006   
3      507  -6  0.14  0.10 -0.2 -10   2  0.001 -0.7 -0.0007 -0.0006 -0.0006   
4     -189 -67 -0.60 -0.08  0.5 -14  17 -0.017 -0.7 -0.0013 -0.0013 -0.0013   
...    ...  ..   ...   ...  ...  ..  ..    ...  ...     ...     ...     ...   
16594 -162 -24  0.27  0.03  0.8 -10   2 -0.009 -0.1 -0.0022 -0.0021 -0.0021   
16595   12 -31  0.20 -0.08 -0.3 -13  12 -0.003  1.3 -0.0008 -0.0008 -0.0008   
16596 -243 -23  0.08 -0.11 -0.7  -7  13  0.007 -0.2 -0.0005 -0.0005 -0.0005   
16597 -226  15 -0.17 -0.01 -0.5  -7   6  0.001 -0.8 -0.0005 -0.0005 -0.0005   
16598 -193  -2 -0.36  0.04 -0.8 -16 -11 -0.026  3.6 -0.0014 -0.0014 -0.0014   

           13      14   15      16   17      18    

In [95]:
#2.3.3

print(data.head(2))

print(data.tail(3))

print(data.shape)

print(data.describe())

print(data.iloc[1:4])

print(data[data["1"] < 0])


     1   2     3     4    5   6   7      8    9      10      11      12  \
0 -178  40 -0.11  0.13  1.1  -9 -12 -0.011  0.0 -0.0007 -0.0007 -0.0007   
1 -122   9  0.27  0.05  0.0 -10  -2 -0.005  0.4 -0.0007 -0.0007 -0.0007   

       13   14   15   16   17      18      y  
0 -0.0007  0.0  0.0  0.0  0.0 -0.0007  0.018  
1 -0.0007  0.0  0.0  0.0  0.0 -0.0007  0.017  
         1   2     3     4    5   6   7      8    9      10      11      12  \
16596 -243 -23  0.08 -0.11 -0.7  -7  13  0.007 -0.2 -0.0005 -0.0005 -0.0005   
16597 -226  15 -0.17 -0.01 -0.5  -7   6  0.001 -0.8 -0.0005 -0.0005 -0.0005   
16598 -193  -2 -0.36  0.04 -0.8 -16 -11 -0.026  3.6 -0.0014 -0.0014 -0.0014   

           13   14   15   16   17      18      y  
16596 -0.0005  0.0  0.0  0.0  0.0 -0.0005  0.033  
16597 -0.0005  0.0  0.0  0.0  0.0 -0.0005  0.016  
16598 -0.0014  0.0  0.0  0.0  0.0 -0.0014  0.018  
(16599, 19)
                  1             2             3             4             5  \
count  16599.000000  

In [103]:
#3.3.2
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
data = pd.read_csv(url)

minmax_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
z_scaler = preprocessing.StandardScaler()

standardized_first = minmax_scaler.fit_transform(data[['sepal_length_cm']])
standardized_second = z_scaler.fit_transform(data[['sepal_width_cm']])

print('First', standardized_first)
print('Second', standardized_second)



First [[0.22222222]
 [0.16666667]
 [0.11111111]
 [0.08333333]
 [0.19444444]
 [0.30555556]
 [0.08333333]
 [0.19444444]
 [0.02777778]
 [0.16666667]
 [0.30555556]
 [0.13888889]
 [0.13888889]
 [0.        ]
 [0.41666667]
 [0.38888889]
 [0.30555556]
 [0.22222222]
 [0.38888889]
 [0.22222222]
 [0.30555556]
 [0.22222222]
 [0.08333333]
 [0.22222222]
 [0.13888889]
 [0.19444444]
 [0.19444444]
 [0.25      ]
 [0.25      ]
 [0.11111111]
 [0.13888889]
 [0.30555556]
 [0.25      ]
 [0.33333333]
 [0.16666667]
 [0.19444444]
 [0.33333333]
 [0.16666667]
 [0.02777778]
 [0.22222222]
 [0.19444444]
 [0.05555556]
 [0.02777778]
 [0.19444444]
 [0.22222222]
 [0.13888889]
 [0.22222222]
 [0.08333333]
 [0.27777778]
 [0.19444444]
 [0.75      ]
 [0.58333333]
 [0.72222222]
 [0.33333333]
 [0.61111111]
 [0.38888889]
 [0.55555556]
 [0.16666667]
 [0.63888889]
 [0.25      ]
 [0.19444444]
 [0.44444444]
 [0.47222222]
 [0.5       ]
 [0.36111111]
 [0.66666667]
 [0.36111111]
 [0.41666667]
 [0.52777778]
 [0.36111111]
 [0.44444444]
